### ISSUE TITLE
Error exports is not defined when try build it

### ISSUE THREAD

**Issue by sieuhuflit** [khevamann/rn-responsive-styles#15]
## Overview

Currently I setup and worked when run dev mode `react-app-rewired start`, but when tried build `react-app-rewired build` and serve then this error come up

<img width="928" alt="Screen Shot 2022-08-14 at 17 28 21" src="https://user-images.githubusercontent.com/7247063/184532788-8caacffa-a103-4ed5-9290-3bffa8653006.png">

<img width="912" alt="Screen Shot 2022-08-14 at 17 28 26" src="https://user-images.githubusercontent.com/7247063/184532791-27ad79ca-3431-4dc0-956d-2e07f79a88f2.png">

**Comment by khevamann** [comment]
@sieuhuflit Just fixed this, it was a tsconfig issue. However, this is made for react-native so using it in `react-app-rewired` will not work unless you have some plans to implement react native with it
