### ISSUE TITLE
Clarify usage of use `useResponsiveStyle`

### ISSUE THREAD

**Issue by stefan-schweiger** [khevamann/rn-responsive-styles#18]
In the code I see that there is a hook called `useResponsiveStyle` but no documentation for it. Can you include a usage example in the README.MD?

**Comment by khevamann** [comment]
Sorry `useResponsiveStyle` is a hook returned from CreateResponsiveStyles, so it can be named whatever. In the README I name it useStyles. I should rename it throughout the codebase so it is a little more straight forward. But basically the return value of CreateResponsiveStyles is the hook `useResponsiveStyle` which I have been naming as `useStyles`. Hope that makes sense

**Comment by stefan-schweiger** [comment]
Makes perfect sense, thank you very much :)
